### ISSUE TITLE
Github markdown highlights not being rendered properly

### ISSUE THREAD

**Issue by mokhosh** [filamentphp/filamentphp.com#341]
Github markdowns have special highlight blocks:
https://github.com/orgs/community/discussions/16925

They're not rendered properly as you can compare here:
https://filamentphp.com/plugins/mokhosh-kanban#before-you-start

with the same block on github itself:
https://github.com/mokhosh/filament-kanban#before-you-start

**Comment by HassanZahirnia** [comment]
Hey, thanks for reporting this!

I think the special highlights are specific to GitHub? Since we use a standard Markdown compiler it doesn't recognize those and I tried some ideas but couldn't get the highlight blocks to render identical to GitHub's.

But I added a specific replacement function to make those blocks look nicer instead of raw text.

Have a look and let me know what you think.

**Comment by mokhosh** [comment]
Looks great @HassanZahirnia jaan. Thanks dadash.
